version: '2.3'
services:
    zookeeper:
        image: debezium/zookeeper:1.6
        ports:
         - 2181:2181
         - 2888:2888
         - 3888:3888
    kafka:
        image: debezium/kafka:1.6
        ports:
         - 9092:9092
        links:
         - zookeeper
        environment:
         - ZOOKEEPER_CONNECT=zookeeper:2181
    schema-registry:
        image: confluentinc/cp-schema-registry
        links:
         - zookeeper
        ports:
         - 8081:8081
        environment:
         - SCHEMA_REGISTRY_HOST_NAME=schema-registry
         - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
         - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
    schema-registry-ui:
        image: landoop/schema-registry-ui
        links:
         - schema-registry
        ports:
         - 8000:8000
        environment:
         - SCHEMAREGISTRY_URL=http://localhost:8081
    connect:
        image: debezium/connect:1.6
        ports:
         - 8083:8083
        links:
         - kafka
         - schema-registry
        environment:
         - BOOTSTRAP_SERVERS=kafka:9092
         - GROUP_ID=1
         - CONFIG_STORAGE_TOPIC=cross_connect_configs
         - OFFSET_STORAGE_TOPIC=cross_connect_offsets
         - STATUS_STORAGE_TOPIC=cross_connect_statuses
