version: '2.3'
services:
    zookeeper:
        image: debezium/zookeeper:1.6
        ports:
         - 2181:2181
         - 2888:2888
         - 3888:3888
    kafka:
        image: debezium/kafka:1.6
        ports:
         - 9092:9092
        links:
         - zookeeper
        environment:
         - ZOOKEEPER_CONNECT=zookeeper:2181
    connect:
        image: debezium/connect:1.6
        ports:
         - 8083:8083
        links:
         - kafka
        environment:
         - BOOTSTRAP_SERVERS=kafka:9092
         - GROUP_ID=1
         - CONFIG_STORAGE_TOPIC=cross_connect_configs
         - OFFSET_STORAGE_TOPIC=cross_connect_offsets
         - STATUS_STORAGE_TOPIC=cross_connect_statuses
