/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cross_ni.cross.cdc.model.source;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** TODO: Represents CROSS Node */
@org.apache.avro.specific.AvroGenerated
public class Node extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1287134262083285161L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Node\",\"namespace\":\"com.cross_ni.cross.cdc.model.source\",\"doc\":\"TODO: Represents CROSS Node\",\"fields\":[{\"name\":\"__op\",\"type\":{\"type\":\"enum\",\"name\":\"Operation\",\"doc\":\"TODO\",\"symbols\":[\"c\",\"r\",\"u\",\"d\"]}},{\"name\":\"node_id\",\"type\":\"long\"},{\"name\":\"ca_set_id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Node> ENCODER =
      new BinaryMessageEncoder<Node>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Node> DECODER =
      new BinaryMessageDecoder<Node>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Node> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Node> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Node> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Node>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Node to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Node from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Node instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Node fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private com.cross_ni.cross.cdc.model.source.Operation __op;
   private long node_id;
   private long ca_set_id;
   private java.lang.String name;
   private java.lang.String description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Node() {}

  /**
   * All-args constructor.
   * @param __op The new value for __op
   * @param node_id The new value for node_id
   * @param ca_set_id The new value for ca_set_id
   * @param name The new value for name
   * @param description The new value for description
   */
  public Node(com.cross_ni.cross.cdc.model.source.Operation __op, java.lang.Long node_id, java.lang.Long ca_set_id, java.lang.String name, java.lang.String description) {
    this.__op = __op;
    this.node_id = node_id;
    this.ca_set_id = ca_set_id;
    this.name = name;
    this.description = description;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return __op;
    case 1: return node_id;
    case 2: return ca_set_id;
    case 3: return name;
    case 4: return description;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: __op = (com.cross_ni.cross.cdc.model.source.Operation)value$; break;
    case 1: node_id = (java.lang.Long)value$; break;
    case 2: ca_set_id = (java.lang.Long)value$; break;
    case 3: name = value$ != null ? value$.toString() : null; break;
    case 4: description = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the '__op' field.
   * @return The value of the '__op' field.
   */
  public com.cross_ni.cross.cdc.model.source.Operation getOp$1() {
    return __op;
  }


  /**
   * Sets the value of the '__op' field.
   * @param value the value to set.
   */
  public void setOp$1(com.cross_ni.cross.cdc.model.source.Operation value) {
    this.__op = value;
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public long getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(long value) {
    this.node_id = value;
  }

  /**
   * Gets the value of the 'ca_set_id' field.
   * @return The value of the 'ca_set_id' field.
   */
  public long getCaSetId() {
    return ca_set_id;
  }


  /**
   * Sets the value of the 'ca_set_id' field.
   * @param value the value to set.
   */
  public void setCaSetId(long value) {
    this.ca_set_id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.String getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.String value) {
    this.description = value;
  }

  /**
   * Creates a new Node RecordBuilder.
   * @return A new Node RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.Node.Builder newBuilder() {
    return new com.cross_ni.cross.cdc.model.source.Node.Builder();
  }

  /**
   * Creates a new Node RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Node RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.Node.Builder newBuilder(com.cross_ni.cross.cdc.model.source.Node.Builder other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.Node.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.Node.Builder(other);
    }
  }

  /**
   * Creates a new Node RecordBuilder by copying an existing Node instance.
   * @param other The existing instance to copy.
   * @return A new Node RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.Node.Builder newBuilder(com.cross_ni.cross.cdc.model.source.Node other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.Node.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.Node.Builder(other);
    }
  }

  /**
   * RecordBuilder for Node instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Node>
    implements org.apache.avro.data.RecordBuilder<Node> {

    private com.cross_ni.cross.cdc.model.source.Operation __op;
    private long node_id;
    private long ca_set_id;
    private java.lang.String name;
    private java.lang.String description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.Node.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.__op)) {
        this.__op = data().deepCopy(fields()[0].schema(), other.__op);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.ca_set_id)) {
        this.ca_set_id = data().deepCopy(fields()[2].schema(), other.ca_set_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Node instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.Node other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.__op)) {
        this.__op = data().deepCopy(fields()[0].schema(), other.__op);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.node_id)) {
        this.node_id = data().deepCopy(fields()[1].schema(), other.node_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ca_set_id)) {
        this.ca_set_id = data().deepCopy(fields()[2].schema(), other.ca_set_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.description)) {
        this.description = data().deepCopy(fields()[4].schema(), other.description);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the '__op' field.
      * @return The value.
      */
    public com.cross_ni.cross.cdc.model.source.Operation getOp$1() {
      return __op;
    }


    /**
      * Sets the value of the '__op' field.
      * @param value The value of '__op'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder setOp$1(com.cross_ni.cross.cdc.model.source.Operation value) {
      validate(fields()[0], value);
      this.__op = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the '__op' field has been set.
      * @return True if the '__op' field has been set, false otherwise.
      */
    public boolean hasOp$1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the '__op' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder clearOp$1() {
      __op = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public long getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder setNodeId(long value) {
      validate(fields()[1], value);
      this.node_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder clearNodeId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ca_set_id' field.
      * @return The value.
      */
    public long getCaSetId() {
      return ca_set_id;
    }


    /**
      * Sets the value of the 'ca_set_id' field.
      * @param value The value of 'ca_set_id'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder setCaSetId(long value) {
      validate(fields()[2], value);
      this.ca_set_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ca_set_id' field has been set.
      * @return True if the 'ca_set_id' field has been set, false otherwise.
      */
    public boolean hasCaSetId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ca_set_id' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder clearCaSetId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder setName(java.lang.String value) {
      validate(fields()[3], value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.String getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder setDescription(java.lang.String value) {
      validate(fields()[4], value);
      this.description = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.Node.Builder clearDescription() {
      description = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Node build() {
      try {
        Node record = new Node();
        record.__op = fieldSetFlags()[0] ? this.__op : (com.cross_ni.cross.cdc.model.source.Operation) defaultValue(fields()[0]);
        record.node_id = fieldSetFlags()[1] ? this.node_id : (java.lang.Long) defaultValue(fields()[1]);
        record.ca_set_id = fieldSetFlags()[2] ? this.ca_set_id : (java.lang.Long) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.String) defaultValue(fields()[3]);
        record.description = fieldSetFlags()[4] ? this.description : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Node>
    WRITER$ = (org.apache.avro.io.DatumWriter<Node>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Node>
    READER$ = (org.apache.avro.io.DatumReader<Node>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.__op.ordinal());

    out.writeLong(this.node_id);

    out.writeLong(this.ca_set_id);

    out.writeString(this.name);

    out.writeString(this.description);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.__op = com.cross_ni.cross.cdc.model.source.Operation.values()[in.readEnum()];

      this.node_id = in.readLong();

      this.ca_set_id = in.readLong();

      this.name = in.readString();

      this.description = in.readString();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.__op = com.cross_ni.cross.cdc.model.source.Operation.values()[in.readEnum()];
          break;

        case 1:
          this.node_id = in.readLong();
          break;

        case 2:
          this.ca_set_id = in.readLong();
          break;

        case 3:
          this.name = in.readString();
          break;

        case 4:
          this.description = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










