/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cross_ni.cross.cdc.model.source;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** TODO: Aggregated */
@org.apache.avro.specific.AvroGenerated
public class NodeTypes extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2679920794625343656L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NodeTypes\",\"namespace\":\"com.cross_ni.cross.cdc.model.source\",\"doc\":\"TODO: Aggregated\",\"fields\":[{\"name\":\"nodeTypes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"NodeType\",\"doc\":\"TODO: Represents CROSS NodeType\",\"fields\":[{\"name\":\"discriminator\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NodeTypes> ENCODER =
      new BinaryMessageEncoder<NodeTypes>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NodeTypes> DECODER =
      new BinaryMessageDecoder<NodeTypes>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NodeTypes> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NodeTypes> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NodeTypes> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NodeTypes>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NodeTypes to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NodeTypes from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NodeTypes instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NodeTypes fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> nodeTypes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NodeTypes() {}

  /**
   * All-args constructor.
   * @param nodeTypes The new value for nodeTypes
   */
  public NodeTypes(java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> nodeTypes) {
    this.nodeTypes = nodeTypes;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nodeTypes;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nodeTypes = (java.util.List<com.cross_ni.cross.cdc.model.source.NodeType>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'nodeTypes' field.
   * @return The value of the 'nodeTypes' field.
   */
  public java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> getNodeTypes() {
    return nodeTypes;
  }


  /**
   * Sets the value of the 'nodeTypes' field.
   * @param value the value to set.
   */
  public void setNodeTypes(java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> value) {
    this.nodeTypes = value;
  }

  /**
   * Creates a new NodeTypes RecordBuilder.
   * @return A new NodeTypes RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeTypes.Builder newBuilder() {
    return new com.cross_ni.cross.cdc.model.source.NodeTypes.Builder();
  }

  /**
   * Creates a new NodeTypes RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NodeTypes RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeTypes.Builder newBuilder(com.cross_ni.cross.cdc.model.source.NodeTypes.Builder other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.NodeTypes.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.NodeTypes.Builder(other);
    }
  }

  /**
   * Creates a new NodeTypes RecordBuilder by copying an existing NodeTypes instance.
   * @param other The existing instance to copy.
   * @return A new NodeTypes RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeTypes.Builder newBuilder(com.cross_ni.cross.cdc.model.source.NodeTypes other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.NodeTypes.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.NodeTypes.Builder(other);
    }
  }

  /**
   * RecordBuilder for NodeTypes instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NodeTypes>
    implements org.apache.avro.data.RecordBuilder<NodeTypes> {

    private java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> nodeTypes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.NodeTypes.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nodeTypes)) {
        this.nodeTypes = data().deepCopy(fields()[0].schema(), other.nodeTypes);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing NodeTypes instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.NodeTypes other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.nodeTypes)) {
        this.nodeTypes = data().deepCopy(fields()[0].schema(), other.nodeTypes);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'nodeTypes' field.
      * @return The value.
      */
    public java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> getNodeTypes() {
      return nodeTypes;
    }


    /**
      * Sets the value of the 'nodeTypes' field.
      * @param value The value of 'nodeTypes'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeTypes.Builder setNodeTypes(java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> value) {
      validate(fields()[0], value);
      this.nodeTypes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nodeTypes' field has been set.
      * @return True if the 'nodeTypes' field has been set, false otherwise.
      */
    public boolean hasNodeTypes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nodeTypes' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeTypes.Builder clearNodeTypes() {
      nodeTypes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NodeTypes build() {
      try {
        NodeTypes record = new NodeTypes();
        record.nodeTypes = fieldSetFlags()[0] ? this.nodeTypes : (java.util.List<com.cross_ni.cross.cdc.model.source.NodeType>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NodeTypes>
    WRITER$ = (org.apache.avro.io.DatumWriter<NodeTypes>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NodeTypes>
    READER$ = (org.apache.avro.io.DatumReader<NodeTypes>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.nodeTypes.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.cross_ni.cross.cdc.model.source.NodeType e0: this.nodeTypes) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> a0 = this.nodeTypes;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType>((int)size0, SCHEMA$.getField("nodeTypes").schema());
        this.nodeTypes = a0;
      } else a0.clear();
      SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.cross_ni.cross.cdc.model.source.NodeType e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.cross_ni.cross.cdc.model.source.NodeType();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.cross_ni.cross.cdc.model.source.NodeType> a0 = this.nodeTypes;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType>((int)size0, SCHEMA$.getField("nodeTypes").schema());
            this.nodeTypes = a0;
          } else a0.clear();
          SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.cross_ni.cross.cdc.model.source.NodeType>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.cross_ni.cross.cdc.model.source.NodeType e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.cross_ni.cross.cdc.model.source.NodeType();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










