/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cross_ni.cross.cdc.model.source;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** TODO: Represents CROSS NodeNodeType */
@org.apache.avro.specific.AvroGenerated
public class NodeNodeType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3957075770727431515L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NodeNodeType\",\"namespace\":\"com.cross_ni.cross.cdc.model.source\",\"doc\":\"TODO: Represents CROSS NodeNodeType\",\"fields\":[{\"name\":\"node_id\",\"type\":\"long\"},{\"name\":\"discriminator\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NodeNodeType> ENCODER =
      new BinaryMessageEncoder<NodeNodeType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NodeNodeType> DECODER =
      new BinaryMessageDecoder<NodeNodeType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NodeNodeType> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NodeNodeType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NodeNodeType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NodeNodeType>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NodeNodeType to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NodeNodeType from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NodeNodeType instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NodeNodeType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long node_id;
   private java.lang.String discriminator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NodeNodeType() {}

  /**
   * All-args constructor.
   * @param node_id The new value for node_id
   * @param discriminator The new value for discriminator
   */
  public NodeNodeType(java.lang.Long node_id, java.lang.String discriminator) {
    this.node_id = node_id;
    this.discriminator = discriminator;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return node_id;
    case 1: return discriminator;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: node_id = (java.lang.Long)value$; break;
    case 1: discriminator = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'node_id' field.
   * @return The value of the 'node_id' field.
   */
  public long getNodeId() {
    return node_id;
  }


  /**
   * Sets the value of the 'node_id' field.
   * @param value the value to set.
   */
  public void setNodeId(long value) {
    this.node_id = value;
  }

  /**
   * Gets the value of the 'discriminator' field.
   * @return The value of the 'discriminator' field.
   */
  public java.lang.String getDiscriminator() {
    return discriminator;
  }


  /**
   * Sets the value of the 'discriminator' field.
   * @param value the value to set.
   */
  public void setDiscriminator(java.lang.String value) {
    this.discriminator = value;
  }

  /**
   * Creates a new NodeNodeType RecordBuilder.
   * @return A new NodeNodeType RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder newBuilder() {
    return new com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder();
  }

  /**
   * Creates a new NodeNodeType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NodeNodeType RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder newBuilder(com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder(other);
    }
  }

  /**
   * Creates a new NodeNodeType RecordBuilder by copying an existing NodeNodeType instance.
   * @param other The existing instance to copy.
   * @return A new NodeNodeType RecordBuilder
   */
  public static com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder newBuilder(com.cross_ni.cross.cdc.model.source.NodeNodeType other) {
    if (other == null) {
      return new com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder();
    } else {
      return new com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder(other);
    }
  }

  /**
   * RecordBuilder for NodeNodeType instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NodeNodeType>
    implements org.apache.avro.data.RecordBuilder<NodeNodeType> {

    private long node_id;
    private java.lang.String discriminator;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.node_id)) {
        this.node_id = data().deepCopy(fields()[0].schema(), other.node_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.discriminator)) {
        this.discriminator = data().deepCopy(fields()[1].schema(), other.discriminator);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing NodeNodeType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cross_ni.cross.cdc.model.source.NodeNodeType other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.node_id)) {
        this.node_id = data().deepCopy(fields()[0].schema(), other.node_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.discriminator)) {
        this.discriminator = data().deepCopy(fields()[1].schema(), other.discriminator);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'node_id' field.
      * @return The value.
      */
    public long getNodeId() {
      return node_id;
    }


    /**
      * Sets the value of the 'node_id' field.
      * @param value The value of 'node_id'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder setNodeId(long value) {
      validate(fields()[0], value);
      this.node_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'node_id' field has been set.
      * @return True if the 'node_id' field has been set, false otherwise.
      */
    public boolean hasNodeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'node_id' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder clearNodeId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'discriminator' field.
      * @return The value.
      */
    public java.lang.String getDiscriminator() {
      return discriminator;
    }


    /**
      * Sets the value of the 'discriminator' field.
      * @param value The value of 'discriminator'.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder setDiscriminator(java.lang.String value) {
      validate(fields()[1], value);
      this.discriminator = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'discriminator' field has been set.
      * @return True if the 'discriminator' field has been set, false otherwise.
      */
    public boolean hasDiscriminator() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'discriminator' field.
      * @return This builder.
      */
    public com.cross_ni.cross.cdc.model.source.NodeNodeType.Builder clearDiscriminator() {
      discriminator = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NodeNodeType build() {
      try {
        NodeNodeType record = new NodeNodeType();
        record.node_id = fieldSetFlags()[0] ? this.node_id : (java.lang.Long) defaultValue(fields()[0]);
        record.discriminator = fieldSetFlags()[1] ? this.discriminator : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NodeNodeType>
    WRITER$ = (org.apache.avro.io.DatumWriter<NodeNodeType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NodeNodeType>
    READER$ = (org.apache.avro.io.DatumReader<NodeNodeType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.node_id);

    out.writeString(this.discriminator);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.node_id = in.readLong();

      this.discriminator = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.node_id = in.readLong();
          break;

        case 1:
          this.discriminator = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










