/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cross_ni.cross.cdc.model.source;
/** TODO */
@org.apache.avro.specific.AvroGenerated
public enum Operation implements org.apache.avro.generic.GenericEnumSymbol<Operation> {
  c, r, u, d  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Operation\",\"namespace\":\"com.cross_ni.cross.cdc.model.source\",\"doc\":\"TODO\",\"symbols\":[\"c\",\"r\",\"u\",\"d\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
